-- AlterTable
ALTER TABLE "Company" ALTER COLUMN "telephone_no" SET DEFAULT '23401802',
ALTER COLUMN "telephone_no" SET DATA TYPE TEXT,
ALTER COLUMN "tin_no" SET DEFAULT '4726828000',
ALTER COLUMN "tin_no" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Person" ALTER COLUMN "contact_no" SET DEFAULT '9632306492',
ALTER COLUMN "contact_no" SET DATA TYPE TEXT;
